
const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
const CLEAR_SEARCH_RESULT = 'CEAR_SEARCH_RESULT';
const UPDATE_MAP_PLACES = 'UPDATE_MAP_PLACES';
const ADD_MARKER = 'ADD_MARKER';
const REMOVE_MARKER = 'REMOVE_MARKER';

export {UPDATE_SEARCH_RESULT, CLEAR_SEARCH_RESULT, UPDATE_MAP_PLACES, ADD_MARKER, REMOVE_MARKER};